import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import App2 from "./App2.jsx";
import App3 from "./App3.jsx";
import App4 from "./App4.jsx";
// import App5 from "./App5.jsx";
// import "./App4.css";
// import "./css/App6.css";
// import App6 from "./App6.jsx";
// import App7 from "./App7.jsx";
// import "./css/App8.css";
// import App8 from "./App8.jsx";
import "./css/Dice.css";
import App9 from "./App9.jsx";
// import Counter from "./components/useRefEX/Counter.jsx";
// import Timer from "./components/useRefEX/Timer.jsx";
createRoot(document.getElementById("root")).render(<App9 />);
